Butler-SOS:
  # Possible log levels are silly, debug, verbose, info, warn, error
  logLevel: verbose

  # Qlik Sense logging db config parameters
  logdb:
    # How often (milliseconds) should Postgres log db be queried for warnings and errors?
    pollingInterval: 15000
    host: senselogdb.ptarmiganlabs.net
    port: 4432
    qlogsReaderUser: qlogs_reader
    qlogsReaderPwd: BvpvIqJMEZ9d

  # Certificates to use when querying Sense for healthcheck data. Get these from the Certificate Export in QMC.
  cert:
    clientCert: C:\\secret\\sense_cert\\client.pem
    clientCertKey: C:\\secret\\sense_cert\\client_key.pem
    clientCertCA: C:\\secret\\sense_cert\\root.pem

  # MQTT config parameters
  mqttConfig:
    enableMQTT: false
    brokerHost: mqtt.ptarmiganlabs.net
    brokerPort: 1883
    # Topic should end with /
    baseTopic: butler-sos/

  # Influx db config parameters
  influxdbConfig:
    enableInfluxdb: true
    hostIP: influxdb.ptarmiganlabs.net
    dbName: SenseOps

  serversToMonitor:
    # How often (milliseconds) should the healthcheck API be polled?
    pollingInterval: 5000

    # Sense Servers that should be queried for healthcheck data 
    servers:
    - host: sense1.ptarmiganlabs.local:4747
      serverName: CENTRAL
      availableRAM: 12000
